title: Kevin Goveas # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  13.5 years of experience in software development, implementation, and support.
  <br>
  Extensive exposure in Application Development using Java, SWT, JFace, Eclipse Plug-in Development, RCP
  <br>
  Expertise in Vue.js and Quasar framework and CSS styling.
  <br>
  Experienced in Core Java, Struts web applications,JSP-1.1, Servlets, eclipse-4.x, Java1.5, Tomcat 5.5, JDBC-3.0, JavaScript, PL/SQL and Oracle 9i/10g.
 
  <br><br>
  <a href="https://www.linkedin.com/in/kevingoveas/">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
