title: Kevin Goveas # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  13.5 years of experience in software development, implementation, and support.
  <br>
  Extensive exposure in Application Development using Java, SWT, JFace, Eclipse Plug-in Development, RCP
  <br>
  Expertise in Vue.js and Quasar framework and CSS styling.
  <br>
  Experienced in Core Java, Struts web applications,JSP-1.1, Servlets, eclipse-4.x, Java1.5, Tomcat 5.5, JDBC-3.0, JavaScript.
  <br>
  Experience working in an Agile software development environment
  <br>
  Experience with the Atlassian Suite of tools (Jira, Confluence.)
  <br>
  Worked with Jest, SWTBot for UI testing, Junit testing using Easy mock.
  <br>
  Worked with PL/SQL and Oracle 9i/10g
  <br>
  Worked with SVN, GIT, Clear case
  <br>
  Currently employed by Fermat Software(on H1B visa)
  <br><br>
  <a href="https://www.linkedin.com/in/kevingoveas/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
