title: Kevin Goveas # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
•	13.5 years of experience in software development, implementation, and support.
  Bachelor of Engineering in Information Technology.
  <br>
  Currently employed by Fermat Software and working at Silicon Labs Austin(on H1B visa)
  <br>
  Second Description 
  <br><br>
  <a href="https://www.linkedin.com/in/kevingoveas/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
